/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */   
package main;
import java.awt.Color;
import java.awt.EventQueue; 
import java.util.ArrayList;
import javax.swing.JFrame; 
import javax.swing.UIManager;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Toolkit;
import javax.swing.JPanel;
import javax.swing.ImageIcon;   
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
/**
 *
 * @author Ugur
 */

public class GUI extends JPanel {

    /**
     * Creates new form NewJPanel
     */
    public JFrame frame;
    public Rectangle solBarRectangle;
    public Rectangle sagBarRectangle;
    public Rectangle ortaBarRectangle;
    public TextAnalyzer textAnalizer;
    public ReverseImage imageAgent;
    public GUI(JFrame frame, TextAnalyzer textAnalizer, ReverseImage imageAgent) {
        initComponents();
        this.frame = frame;
        this.textAnalizer =  textAnalizer;
        this.imageAgent = imageAgent;
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private ArrayList<String> getPersonNames(String URL){
        ArrayList<String> list = imageAgent.findByURL(URL,1);   
        list = removeDuplicates(list); 
        list.removeIf(s -> s.contains("https://webcache.googleusercontent.com/search?q"));
        list.remove("#");
        ArrayList<String> persons = textAnalizer.getPersons(list);  
        
        System.out.println(persons.get(0));
        return persons;        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        kButton1 = new keeptoo.KButton();
        kButton2 = new keeptoo.KButton();
        kButton3 = new keeptoo.KButton();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        Closebtn = new javax.swing.JLabel();
        MaximizeBtn = new javax.swing.JLabel();
        MinimizeBtn = new javax.swing.JLabel();
        Content2 = new javax.swing.JPanel();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        K1 = new javax.swing.JLabel();
        URLField = new javax.swing.JTextField();
        SearchButton = new keeptoo.KButton();
        Table = new keeptoo.KGradientPanel();
        ResultPanel1 = new keeptoo.KGradientPanel();
        Result1 = new javax.swing.JLabel();
        ResultPanel2 = new keeptoo.KGradientPanel();
        Result2 = new javax.swing.JLabel();
        ResultPanel3 = new keeptoo.KGradientPanel();
        Result3 = new javax.swing.JLabel();
        ResultPanel4 = new keeptoo.KGradientPanel();
        Result4 = new javax.swing.JLabel();
        ResultPanel5 = new keeptoo.KGradientPanel();
        Result5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ImageDisplayPanel = new keeptoo.KGradientPanel();
        ImageDisplay = new javax.swing.JLabel();
        Content1 = new javax.swing.JPanel();
        kGradientPanel7 = new keeptoo.KGradientPanel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        kGradientPanel10 = new keeptoo.KGradientPanel();
        kGradientPanel6 = new keeptoo.KGradientPanel();
        Content3 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(2, 14, 28));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(47, 38, 88));
        kGradientPanel1.setkStartColor(new java.awt.Color(47, 38, 88));
        kGradientPanel1.setkTransparentControls(false);
        kGradientPanel1.setLayout(new java.awt.GridLayout(5, 2, 10, 4));

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );

        kGradientPanel1.add(jLayeredPane1);

        kButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 38, 88)));
        kButton1.setkBorderRadius(0);
        kButton1.setkEndColor(new java.awt.Color(0, 103, 103));
        kButton1.setkHoverEndColor(new java.awt.Color(38, 31, 70));
        kButton1.setkHoverForeGround(new java.awt.Color(38, 31, 70));
        kButton1.setkHoverStartColor(new java.awt.Color(38, 31, 70));
        kButton1.setkStartColor(new java.awt.Color(17, 78, 128));
        kButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                content1(evt);
            }
        });
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton1);

        kButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 38, 88)));
        kButton2.setkBorderRadius(0);
        kButton2.setkEndColor(new java.awt.Color(0, 103, 103));
        kButton2.setkHoverEndColor(new java.awt.Color(38, 31, 70));
        kButton2.setkHoverForeGround(new java.awt.Color(38, 31, 70));
        kButton2.setkHoverStartColor(new java.awt.Color(38, 31, 70));
        kButton2.setkStartColor(new java.awt.Color(17, 78, 128));
        kButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                content2(evt);
            }
        });
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton2);

        kButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 38, 88)));
        kButton3.setkBorderRadius(0);
        kButton3.setkEndColor(new java.awt.Color(0, 103, 103));
        kButton3.setkHoverEndColor(new java.awt.Color(38, 31, 70));
        kButton3.setkHoverForeGround(new java.awt.Color(38, 31, 70));
        kButton3.setkHoverStartColor(new java.awt.Color(38, 31, 70));
        kButton3.setkStartColor(new java.awt.Color(17, 78, 128));
        kButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                content3(evt);
            }
        });
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton3);

        add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 60, 630));

        kGradientPanel2.setBackground(new java.awt.Color(210, 210, 240));
        kGradientPanel2.setkBorderRadius(0);
        kGradientPanel2.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel2.setkGradientFocus(800);
        kGradientPanel2.setkStartColor(new java.awt.Color(47, 38, 88));
        kGradientPanel2.setkTransparentControls(false);

        Closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close-window-50.png"))); // NOI18N
        Closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Exit(evt);
            }
        });

        MaximizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-maximize-window-50.png"))); // NOI18N
        MaximizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Maximize(evt);
            }
        });

        MinimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-minimize-window-50.png"))); // NOI18N
        MinimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(1268, Short.MAX_VALUE)
                .addComponent(MinimizeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MaximizeBtn)
                .addGap(10, 10, 10)
                .addComponent(Closebtn)
                .addGap(2, 2, 2))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Closebtn)
                    .addComponent(MaximizeBtn)
                    .addComponent(MinimizeBtn))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1290, 50));

        Content2.setBackground(new java.awt.Color(38, 31, 70));

        kGradientPanel5.setBackground(new java.awt.Color(2, 14, 28));
        kGradientPanel5.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel5.setkStartColor(new java.awt.Color(47, 38, 88));

        jPanel1.setBackground(new java.awt.Color(2, 14, 28));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel3.setBackground(new java.awt.Color(210, 210, 240));
        kGradientPanel3.setkBorderRadius(0);
        kGradientPanel3.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel3.setkGradientFocus(800);
        kGradientPanel3.setkStartColor(new java.awt.Color(47, 38, 88));
        kGradientPanel3.setkTransparentControls(false);
        kGradientPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        K1.setForeground(new java.awt.Color(255, 255, 255));
        K1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-40.png"))); // NOI18N
        K1.setText(" ");
        kGradientPanel3.add(K1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 50, -1));

        jPanel1.add(kGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 40));

        URLField.setText("Enter Image URL");
        URLField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URLFieldActionPerformed(evt);
            }
        });
        jPanel1.add(URLField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 420, 30));

        SearchButton.setBorder(null);
        SearchButton.setText("Search");
        SearchButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SearchButton.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        SearchButton.setkBorderRadius(2);
        SearchButton.setkEndColor(new java.awt.Color(0, 0, 0));
        SearchButton.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        SearchButton.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        SearchButton.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        SearchButton.setkSelectedColor(new java.awt.Color(255, 255, 255));
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        SearchButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SearchButtonKeyPressed(evt);
            }
        });
        jPanel1.add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, -1, -1));

        Table.setBackground(new java.awt.Color(38, 31, 70));
        Table.setkBorderRadius(0);
        Table.setkEndColor(new java.awt.Color(0, 153, 153));
        Table.setkGradientFocus(120);
        Table.setkStartColor(new java.awt.Color(38, 31, 70));
        Table.setkTransparentControls(false);
        Table.setPreferredSize(new java.awt.Dimension(500, 500));
        Table.setLayout(new java.awt.GridLayout(5, 5, 0, 4));

        ResultPanel1.setBackground(new java.awt.Color(38, 31, 70));
        ResultPanel1.setkBorderRadius(0);
        ResultPanel1.setkEndColor(new java.awt.Color(0, 153, 153));
        ResultPanel1.setkGradientFocus(120);
        ResultPanel1.setkStartColor(new java.awt.Color(38, 31, 70));
        ResultPanel1.setkTransparentControls(false);
        ResultPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        ResultPanel1.setLayout(null);

        Result1.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        Result1.setForeground(new java.awt.Color(255, 255, 255));
        Result1.setText(" ");
        ResultPanel1.add(Result1);
        Result1.setBounds(50, 20, 150, 50);

        Table.add(ResultPanel1);

        ResultPanel2.setBackground(new java.awt.Color(38, 31, 70));
        ResultPanel2.setkBorderRadius(0);
        ResultPanel2.setkEndColor(new java.awt.Color(0, 153, 153));
        ResultPanel2.setkGradientFocus(120);
        ResultPanel2.setkStartColor(new java.awt.Color(38, 31, 70));
        ResultPanel2.setkTransparentControls(false);
        ResultPanel2.setPreferredSize(new java.awt.Dimension(500, 500));
        ResultPanel2.setLayout(null);

        Result2.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        Result2.setForeground(new java.awt.Color(255, 255, 255));
        Result2.setText(" ");
        ResultPanel2.add(Result2);
        Result2.setBounds(50, 20, 150, 50);

        Table.add(ResultPanel2);

        ResultPanel3.setBackground(new java.awt.Color(38, 31, 70));
        ResultPanel3.setkBorderRadius(0);
        ResultPanel3.setkEndColor(new java.awt.Color(0, 153, 153));
        ResultPanel3.setkGradientFocus(120);
        ResultPanel3.setkStartColor(new java.awt.Color(38, 31, 70));
        ResultPanel3.setkTransparentControls(false);
        ResultPanel3.setPreferredSize(new java.awt.Dimension(500, 500));
        ResultPanel3.setLayout(null);

        Result3.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        Result3.setForeground(new java.awt.Color(255, 255, 255));
        Result3.setText(" ");
        ResultPanel3.add(Result3);
        Result3.setBounds(50, 20, 150, 50);

        Table.add(ResultPanel3);

        ResultPanel4.setBackground(new java.awt.Color(38, 31, 70));
        ResultPanel4.setkBorderRadius(0);
        ResultPanel4.setkEndColor(new java.awt.Color(0, 153, 153));
        ResultPanel4.setkGradientFocus(120);
        ResultPanel4.setkStartColor(new java.awt.Color(38, 31, 70));
        ResultPanel4.setkTransparentControls(false);
        ResultPanel4.setPreferredSize(new java.awt.Dimension(500, 500));
        ResultPanel4.setLayout(null);

        Result4.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        Result4.setForeground(new java.awt.Color(255, 255, 255));
        Result4.setText(" ");
        ResultPanel4.add(Result4);
        Result4.setBounds(50, 20, 150, 50);

        Table.add(ResultPanel4);

        ResultPanel5.setBackground(new java.awt.Color(38, 31, 70));
        ResultPanel5.setkBorderRadius(0);
        ResultPanel5.setkEndColor(new java.awt.Color(0, 153, 153));
        ResultPanel5.setkGradientFocus(120);
        ResultPanel5.setkStartColor(new java.awt.Color(38, 31, 70));
        ResultPanel5.setkTransparentControls(false);
        ResultPanel5.setPreferredSize(new java.awt.Dimension(500, 500));
        ResultPanel5.setLayout(null);

        Result5.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        Result5.setForeground(new java.awt.Color(255, 255, 255));
        Result5.setText(" ");
        ResultPanel5.add(Result5);
        Result5.setBounds(50, 20, 150, 50);

        Table.add(ResultPanel5);

        jPanel1.add(Table, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 220, 510));

        ImageDisplayPanel.setBackground(new java.awt.Color(38, 31, 70));
        ImageDisplayPanel.setkBorderRadius(0);
        ImageDisplayPanel.setkEndColor(new java.awt.Color(0, 153, 153));
        ImageDisplayPanel.setkGradientFocus(120);
        ImageDisplayPanel.setkStartColor(new java.awt.Color(38, 31, 70));
        ImageDisplayPanel.setkTransparentControls(false);
        ImageDisplayPanel.setPreferredSize(new java.awt.Dimension(500, 500));
        ImageDisplayPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImageDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageDisplay.setText("     ");
        ImageDisplay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ImageDisplayPanel.add(ImageDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImageDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ImageDisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 530, 290));

        javax.swing.GroupLayout kGradientPanel5Layout = new javax.swing.GroupLayout(kGradientPanel5);
        kGradientPanel5.setLayout(kGradientPanel5Layout);
        kGradientPanel5Layout.setHorizontalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        kGradientPanel5Layout.setVerticalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Content2Layout = new javax.swing.GroupLayout(Content2);
        Content2.setLayout(Content2Layout);
        Content2Layout.setHorizontalGroup(
            Content2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
        );
        Content2Layout.setVerticalGroup(
            Content2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Content2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kGradientPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(Content2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 930, 560));

        Content1.setBackground(new java.awt.Color(2, 14, 28));
        Content1.setLayout(new java.awt.GridLayout(2, 2, 80, 80));

        kGradientPanel7.setBackground(new java.awt.Color(38, 31, 70));
        kGradientPanel7.setkBorderRadius(0);
        kGradientPanel7.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel7.setkGradientFocus(120);
        kGradientPanel7.setkStartColor(new java.awt.Color(38, 31, 70));
        kGradientPanel7.setkTransparentControls(false);
        kGradientPanel7.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout kGradientPanel7Layout = new javax.swing.GroupLayout(kGradientPanel7);
        kGradientPanel7.setLayout(kGradientPanel7Layout);
        kGradientPanel7Layout.setHorizontalGroup(
            kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );
        kGradientPanel7Layout.setVerticalGroup(
            kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        Content1.add(kGradientPanel7);

        kGradientPanel4.setBackground(new java.awt.Color(38, 31, 70));
        kGradientPanel4.setkBorderRadius(0);
        kGradientPanel4.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel4.setkGradientFocus(120);
        kGradientPanel4.setkStartColor(new java.awt.Color(38, 31, 70));
        kGradientPanel4.setkTransparentControls(false);
        kGradientPanel4.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        Content1.add(kGradientPanel4);

        kGradientPanel10.setBackground(new java.awt.Color(38, 31, 70));
        kGradientPanel10.setkBorderRadius(0);
        kGradientPanel10.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel10.setkGradientFocus(120);
        kGradientPanel10.setkStartColor(new java.awt.Color(38, 31, 70));
        kGradientPanel10.setkTransparentControls(false);
        kGradientPanel10.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout kGradientPanel10Layout = new javax.swing.GroupLayout(kGradientPanel10);
        kGradientPanel10.setLayout(kGradientPanel10Layout);
        kGradientPanel10Layout.setHorizontalGroup(
            kGradientPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );
        kGradientPanel10Layout.setVerticalGroup(
            kGradientPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        Content1.add(kGradientPanel10);

        kGradientPanel6.setBackground(new java.awt.Color(38, 31, 70));
        kGradientPanel6.setkBorderRadius(0);
        kGradientPanel6.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel6.setkGradientFocus(120);
        kGradientPanel6.setkStartColor(new java.awt.Color(38, 31, 70));
        kGradientPanel6.setkTransparentControls(false);
        kGradientPanel6.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout kGradientPanel6Layout = new javax.swing.GroupLayout(kGradientPanel6);
        kGradientPanel6.setLayout(kGradientPanel6Layout);
        kGradientPanel6Layout.setHorizontalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );
        kGradientPanel6Layout.setVerticalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        Content1.add(kGradientPanel6);

        add(Content1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 930, 560));

        Content3.setBackground(new java.awt.Color(38, 31, 70));

        javax.swing.GroupLayout Content3Layout = new javax.swing.GroupLayout(Content3);
        Content3.setLayout(Content3Layout);
        Content3Layout.setHorizontalGroup(
            Content3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );
        Content3Layout.setVerticalGroup(
            Content3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        add(Content3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 930, 560));
    }// </editor-fold>//GEN-END:initComponents

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton2ActionPerformed

    private void Exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit
        // TODO add your handling code here:
           
        frame.dispose();
        
    }//GEN-LAST:event_Exit
    private void Maximize(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Maximize
        // TODO add your handling code here:
        if(frame.getExtendedState()==JFrame.NORMAL)
            frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        else
            frame.setExtendedState(JFrame.NORMAL);
    }//GEN-LAST:event_Maximize

    private void Minimize(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize
        // TODO add your handling code here:
        frame.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize
    private void setImage(javax.swing.JLabel label,String ImagePath,int w, int h){
        ImageIcon myImage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource(ImagePath))); 
        Image img1 = myImage.getImage();
        Image img2 = img1.getScaledInstance(w,h,Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);
        label.setIcon(i);
    }  
    private void content1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_content1
        // TODO add your handling code here:
        Content3.setVisible(false);
        Content2.setVisible(false);
        Content1.setVisible(true);
        kButton3.setkFillButton(true);
        kButton2.setkFillButton(true);
        kButton1.setkFillButton(false);
        
    }//GEN-LAST:event_content1


    private void content2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_content2
        // TODO add your handling code here:
        Content3.setVisible(false);
        Content2.setVisible(true);
        Content1.setVisible(false);
        
        /*Content2.setLocation(-5000, -5000); SONRADAN SET VİSİBLE İLE DEĞİŞTİRECEĞİZ 
        ÇÜNKÜ SET VİSİBLE FONKSİYONU PNELİ YENİDEN ÇİZİYOR BU YÜZDEN INDİCATOR DEĞERİ DEFAULT KONUMA GERİ DÖNÜYOR
        
        
        */
        
        kButton3.setkFillButton(true);
        kButton2.setkFillButton(false);
        kButton1.setkFillButton(true); 






    }//GEN-LAST:event_content2

    private void content3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_content3
        // TODO add your handling code here:
        Content3.setVisible(true);
        Content2.setVisible(false);
        Content1.setVisible(false);
        kButton3.setkFillButton(false);
        kButton2.setkFillButton(true);
        kButton1.setkFillButton(true);

    }//GEN-LAST:event_content3

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton3ActionPerformed

    private void URLFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URLFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_URLFieldActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        String URL = URLField.getText();
        try{
            URL url = new URL(URL);
            BufferedImage image = ImageIO.read(url);
            int w = image.getWidth();
            int h = image.getHeight();
            float ratio = (float)w/(float)h;
            int pw =ImageDisplayPanel.getWidth();
            int ph = ImageDisplayPanel.getHeight(); 
            if(w>h){
                w = pw;
                h = (int)(ratio/w);
            }
            else{
                h = ph;
                w = (int)(ratio*h);
            }
                
            Image dimg = image.getScaledInstance(pw , ph  ,
        Image.SCALE_SMOOTH);
            ImageDisplay.setIcon(new ImageIcon(dimg));
        }
        catch(Exception e){
            e.printStackTrace();
            System.out.println("Görüntü Yüklenemedi");
        } 
        
        /*ArrayList<String> persons = getPersonNames(URL);
            
        Result1.setText(persons.get(0));
        Result2.setText(persons.get(1));
        Result3.setText(persons.get(2));
        Result4.setText(persons.get(3));
        Result5.setText(persons.get(4));*/
           
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void SearchButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchButtonKeyPressed
        
    }//GEN-LAST:event_SearchButtonKeyPressed
    public static <T> ArrayList<T> removeDuplicates(ArrayList<T> list) 
    { 
  
        // Create a new ArrayList 
        ArrayList<T> newList = new ArrayList<T>(); 
  
        // Traverse through the first list 
        for (T element : list) { 
  
            // If this element is not present in newList 
            // then add it 
            if (!newList.contains(element)) { 
  
                newList.add(element); 
            } 
        } 
  
        // return the new list 
        return newList; 
    } 
    
    public static void main(String[] args) {
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               
                
                String API_KEY = "b4176007bbmsh019a5302dfbf37ep128a44jsne61077ecbeee"; 
                JFrame frame = new JFrame("Testing");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setUndecorated(true);
                frame.setResizable(true);
                 
                
                ReverseImage imageAgent = new ReverseImage(API_KEY);
                TextAnalyzer textAnalizer = new TextAnalyzer(API_KEY); 
                GUI GUI = new GUI( frame,textAnalizer,imageAgent);
                frame.add(GUI);
                
                frame.pack();
                frame.setLocationRelativeTo(null);
                UIManager.put("JFrame.activeTitleBackground", Color.red);
                
                frame.setVisible(true); 

            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Closebtn;
    public static javax.swing.JPanel Content1;
    private static javax.swing.JPanel Content2;
    private static javax.swing.JPanel Content3;
    private javax.swing.JLabel ImageDisplay;
    private keeptoo.KGradientPanel ImageDisplayPanel;
    private javax.swing.JLabel K1;
    private javax.swing.JLabel MaximizeBtn;
    private javax.swing.JLabel MinimizeBtn;
    private javax.swing.JLabel Result1;
    private javax.swing.JLabel Result2;
    private javax.swing.JLabel Result3;
    private javax.swing.JLabel Result4;
    private javax.swing.JLabel Result5;
    private keeptoo.KGradientPanel ResultPanel1;
    private keeptoo.KGradientPanel ResultPanel2;
    private keeptoo.KGradientPanel ResultPanel3;
    private keeptoo.KGradientPanel ResultPanel4;
    private keeptoo.KGradientPanel ResultPanel5;
    private keeptoo.KButton SearchButton;
    private keeptoo.KGradientPanel Table;
    private javax.swing.JTextField URLField;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private keeptoo.KButton kButton1;
    private keeptoo.KButton kButton2;
    private keeptoo.KButton kButton3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel10;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel5;
    private keeptoo.KGradientPanel kGradientPanel6;
    private keeptoo.KGradientPanel kGradientPanel7;
    // End of variables declaration//GEN-END:variables
}
