/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */   
import keeptoo.ReverseImage;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Toolkit;
import javax.swing.JPanel;
import javax.swing.ImageIcon; 
import  keeptoo.KGradientPanel;
import  keeptoo.KButton;
import javax.swing.text.html.ImageView; 


/**
 *
 * @author Ugur
 */
public class GUI extends JPanel {

    /**
     * Creates new form NewJPanel
     */
    public JFrame frame;
    public Rectangle solBarRectangle;
    public Rectangle sagBarRectangle;
    public Rectangle ortaBarRectangle;
    
    public GUI(JFrame frame) {
        initComponents();
        this.frame = frame;
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        kButton1 = new keeptoo.KButton();
        kButton2 = new keeptoo.KButton();
        kButton3 = new keeptoo.KButton();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        Closebtn = new javax.swing.JLabel();
        MaximizeBtn = new javax.swing.JLabel();
        MinimizeBtn = new javax.swing.JLabel();
        Content1 = new javax.swing.JPanel();
        kGradientPanel7 = new keeptoo.KGradientPanel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        kGradientPanel10 = new keeptoo.KGradientPanel();
        kGradientPanel6 = new keeptoo.KGradientPanel();
        Content2 = new javax.swing.JPanel();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        K = new javax.swing.JLabel();
        Content3 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(2, 14, 28));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(47, 38, 88));
        kGradientPanel1.setkStartColor(new java.awt.Color(47, 38, 88));
        kGradientPanel1.setkTransparentControls(false);
        kGradientPanel1.setLayout(new java.awt.GridLayout(5, 2, 10, 4));

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );

        kGradientPanel1.add(jLayeredPane1);

        kButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 38, 88)));
        kButton1.setkBorderRadius(0);
        kButton1.setkEndColor(new java.awt.Color(0, 103, 103));
        kButton1.setkHoverEndColor(new java.awt.Color(38, 31, 70));
        kButton1.setkHoverForeGround(new java.awt.Color(38, 31, 70));
        kButton1.setkHoverStartColor(new java.awt.Color(38, 31, 70));
        kButton1.setkStartColor(new java.awt.Color(17, 78, 128));
        kButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                content1(evt);
            }
        });
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton1);

        kButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 38, 88)));
        kButton2.setkBorderRadius(0);
        kButton2.setkEndColor(new java.awt.Color(0, 103, 103));
        kButton2.setkHoverEndColor(new java.awt.Color(38, 31, 70));
        kButton2.setkHoverForeGround(new java.awt.Color(38, 31, 70));
        kButton2.setkHoverStartColor(new java.awt.Color(38, 31, 70));
        kButton2.setkStartColor(new java.awt.Color(17, 78, 128));
        kButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                content2(evt);
            }
        });
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton2);

        kButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 38, 88)));
        kButton3.setkBorderRadius(0);
        kButton3.setkEndColor(new java.awt.Color(0, 103, 103));
        kButton3.setkHoverEndColor(new java.awt.Color(38, 31, 70));
        kButton3.setkHoverForeGround(new java.awt.Color(38, 31, 70));
        kButton3.setkHoverStartColor(new java.awt.Color(38, 31, 70));
        kButton3.setkStartColor(new java.awt.Color(17, 78, 128));
        kButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                content3(evt);
            }
        });
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton3);

        add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 60, 630));

        kGradientPanel2.setBackground(new java.awt.Color(210, 210, 240));
        kGradientPanel2.setkBorderRadius(0);
        kGradientPanel2.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel2.setkGradientFocus(800);
        kGradientPanel2.setkStartColor(new java.awt.Color(47, 38, 88));
        kGradientPanel2.setkTransparentControls(false);

        Closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close-window-50.png"))); // NOI18N
        Closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Exit(evt);
            }
        });

        MaximizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-maximize-window-50.png"))); // NOI18N
        MaximizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Maximize(evt);
            }
        });

        MinimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-minimize-window-50.png"))); // NOI18N
        MinimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Minimize(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(1268, Short.MAX_VALUE)
                .addComponent(MinimizeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MaximizeBtn)
                .addGap(10, 10, 10)
                .addComponent(Closebtn)
                .addGap(2, 2, 2))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Closebtn)
                    .addComponent(MaximizeBtn)
                    .addComponent(MinimizeBtn))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1290, 50));

        Content1.setBackground(new java.awt.Color(2, 14, 28));
        Content1.setLayout(new java.awt.GridLayout(2, 2, 80, 80));

        kGradientPanel7.setBackground(new java.awt.Color(38, 31, 70));
        kGradientPanel7.setkBorderRadius(0);
        kGradientPanel7.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel7.setkGradientFocus(120);
        kGradientPanel7.setkStartColor(new java.awt.Color(38, 31, 70));
        kGradientPanel7.setkTransparentControls(false);
        kGradientPanel7.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout kGradientPanel7Layout = new javax.swing.GroupLayout(kGradientPanel7);
        kGradientPanel7.setLayout(kGradientPanel7Layout);
        kGradientPanel7Layout.setHorizontalGroup(
            kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );
        kGradientPanel7Layout.setVerticalGroup(
            kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        Content1.add(kGradientPanel7);

        kGradientPanel4.setBackground(new java.awt.Color(38, 31, 70));
        kGradientPanel4.setkBorderRadius(0);
        kGradientPanel4.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel4.setkGradientFocus(120);
        kGradientPanel4.setkStartColor(new java.awt.Color(38, 31, 70));
        kGradientPanel4.setkTransparentControls(false);
        kGradientPanel4.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        Content1.add(kGradientPanel4);

        kGradientPanel10.setBackground(new java.awt.Color(38, 31, 70));
        kGradientPanel10.setkBorderRadius(0);
        kGradientPanel10.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel10.setkGradientFocus(120);
        kGradientPanel10.setkStartColor(new java.awt.Color(38, 31, 70));
        kGradientPanel10.setkTransparentControls(false);
        kGradientPanel10.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout kGradientPanel10Layout = new javax.swing.GroupLayout(kGradientPanel10);
        kGradientPanel10.setLayout(kGradientPanel10Layout);
        kGradientPanel10Layout.setHorizontalGroup(
            kGradientPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );
        kGradientPanel10Layout.setVerticalGroup(
            kGradientPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        Content1.add(kGradientPanel10);

        kGradientPanel6.setBackground(new java.awt.Color(38, 31, 70));
        kGradientPanel6.setkBorderRadius(0);
        kGradientPanel6.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel6.setkGradientFocus(120);
        kGradientPanel6.setkStartColor(new java.awt.Color(38, 31, 70));
        kGradientPanel6.setkTransparentControls(false);
        kGradientPanel6.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout kGradientPanel6Layout = new javax.swing.GroupLayout(kGradientPanel6);
        kGradientPanel6.setLayout(kGradientPanel6Layout);
        kGradientPanel6Layout.setHorizontalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );
        kGradientPanel6Layout.setVerticalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        Content1.add(kGradientPanel6);

        add(Content1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 930, 560));

        Content2.setBackground(new java.awt.Color(38, 31, 70));

        kGradientPanel5.setBackground(new java.awt.Color(2, 14, 28));
        kGradientPanel5.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel5.setkStartColor(new java.awt.Color(47, 38, 88));

        jPanel1.setBackground(new java.awt.Color(2, 14, 28));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel3.setBackground(new java.awt.Color(210, 210, 240));
        kGradientPanel3.setkBorderRadius(0);
        kGradientPanel3.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel3.setkGradientFocus(800);
        kGradientPanel3.setkStartColor(new java.awt.Color(47, 38, 88));
        kGradientPanel3.setkTransparentControls(false);

        K.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Indicator Icon.png"))); // NOI18N
        K.setText("              ");

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(424, 424, 424)
                .addComponent(K, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(436, Short.MAX_VALUE))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(K, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(kGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 40));

        javax.swing.GroupLayout kGradientPanel5Layout = new javax.swing.GroupLayout(kGradientPanel5);
        kGradientPanel5.setLayout(kGradientPanel5Layout);
        kGradientPanel5Layout.setHorizontalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        kGradientPanel5Layout.setVerticalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Content2Layout = new javax.swing.GroupLayout(Content2);
        Content2.setLayout(Content2Layout);
        Content2Layout.setHorizontalGroup(
            Content2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
        );
        Content2Layout.setVerticalGroup(
            Content2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Content2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kGradientPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(Content2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 930, 560));

        Content3.setBackground(new java.awt.Color(38, 31, 70));

        javax.swing.GroupLayout Content3Layout = new javax.swing.GroupLayout(Content3);
        Content3.setLayout(Content3Layout);
        Content3Layout.setHorizontalGroup(
            Content3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );
        Content3Layout.setVerticalGroup(
            Content3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        add(Content3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 930, 560));
    }// </editor-fold>//GEN-END:initComponents

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton2ActionPerformed

    private void Exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit
        // TODO add your handling code here:
           
        frame.dispose();
        
    }//GEN-LAST:event_Exit
    private void Maximize(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Maximize
        // TODO add your handling code here:
        if(frame.getExtendedState()==JFrame.NORMAL)
            frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        else
            frame.setExtendedState(JFrame.NORMAL);
    }//GEN-LAST:event_Maximize

    private void Minimize(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize
        // TODO add your handling code here:
        frame.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_Minimize
    private void setImage(javax.swing.JLabel label,String ImagePath,int w, int h){
        ImageIcon myImage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource(ImagePath))); 
        Image img1 = myImage.getImage();
        Image img2 = img1.getScaledInstance(w,h,Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);
        label.setIcon(i);
    }  
    private void content1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_content1
        // TODO add your handling code here:
        Content3.setVisible(false);
        Content2.setVisible(false);
        Content1.setVisible(true);
        kButton3.setkFillButton(true);
        kButton2.setkFillButton(true);
        kButton1.setkFillButton(false);
        
    }//GEN-LAST:event_content1


    private void content2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_content2
        // TODO add your handling code here:
        Content3.setVisible(false);
        Content2.setVisible(true);
        Content1.setVisible(false);
        
        /*Content2.setLocation(-5000, -5000); SONRADAN SET VİSİBLE İLE DEĞİŞTİRECEĞİZ 
        ÇÜNKÜ SET VİSİBLE FONKSİYONU PNELİ YENİDEN ÇİZİYOR BU YÜZDEN INDİCATOR DEĞERİ DEFAULT KONUMA GERİ DÖNÜYOR
        
        
        */
        
        kButton3.setkFillButton(true);
        kButton2.setkFillButton(false);
        kButton1.setkFillButton(true); 






    }//GEN-LAST:event_content2

    private void content3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_content3
        // TODO add your handling code here:
        Content3.setVisible(true);
        Content2.setVisible(false);
        Content1.setVisible(false);
        kButton3.setkFillButton(false);
        kButton2.setkFillButton(true);
        kButton1.setkFillButton(true);

    }//GEN-LAST:event_content3

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton3ActionPerformed
public static void main(String[] args) {
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                String API_KEY = "b4176007bbmsh019a5302dfbf37ep128a44jsne61077ecbeee";
                ReverseImage imageAgent = new ReverseImage(API_KEY);
                String imagePath = "https://www.talkwalker.com/images/2020/blog-headers/image-analysis.png";
                imageAgent.findByURL(imagePath);
                String result = imageAgent.getResponse(imagePath);
                System.out.println(result);
                
                
                JFrame frame = new JFrame("Testing");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setUndecorated(true);
                frame.setResizable(true);
                
                //Bunu kullanmadım, Indicator. java şu an bir işe yramıyor  
                
                GUI GUI = new GUI(frame);
                frame.add(GUI);
                
                frame.pack();
                frame.setLocationRelativeTo(null);
                UIManager.put("JFrame.activeTitleBackground", Color.red);
                
                frame.setVisible(true); 

            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Closebtn;
    public static javax.swing.JPanel Content1;
    private static javax.swing.JPanel Content2;
    private static javax.swing.JPanel Content3;
    private javax.swing.JLabel K;
    private javax.swing.JLabel MaximizeBtn;
    private javax.swing.JLabel MinimizeBtn;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KButton kButton1;
    private keeptoo.KButton kButton2;
    private keeptoo.KButton kButton3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel10;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel5;
    private keeptoo.KGradientPanel kGradientPanel6;
    private keeptoo.KGradientPanel kGradientPanel7;
    // End of variables declaration//GEN-END:variables
}
